### PR TITLE
fix: error handling when querying for microphone permission

### LINKED ISSUE #719: Sender: 'microphone' is not a valid value for enumeration PermissionName.
## Description

When the Sender component is used in a browser which does not have the 'microphone' in `PermissionName`, an error is logged to the console. Full support for the 'microphone' permission was only added to firefox in version 132, in October 2024.

```
TypeError: 'microphone' (value of 'name' member of PermissionDescriptor) is not a valid value for enumeration PermissionName.
```

This is caused by [this section](https://github.com/ant-design/x/blob/87246f3304b7a847e273f07fe263b08ac0f4fe18/components/sender/useSpeech.ts#L46) of the `useSpeech.ts` file.

## How to reproduce

- Create a Sender component and open on a < 132 firefox browser.  (I discovered this issue on version 130)

### PR DESCRIPTION
**Pull request by seanparmelee**
[中文版模板 / Chinese template](https://github.com/ant-design/x/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ⌨️ Accessibility improvement
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

Fixes #719

### 💡 Background and Solution

Ou application is using the `Sender` component, but not the speech feature. Regardless, if a user happens to be on a 
[browsers that doesn't support the `microphone` permission](https://caniuse.com/mdn-api_permissions_permission_microphone), they will see an error in their console and we will see the error in Sentry. Our application is still usable when this error occurs, but it would be nice to not see this error since there's nothing we can do about it. This PR adds a `catch` for this scenario and uses the `warning` utility to display the caught error in development environments.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://x.ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fixed `Sender` error handling when querying for `microphone` permission.         |
| 🇨🇳 Chinese |           |

## Summary by CodeRabbit

* **Bug 修复**
  * 增强了麦克风权限查询的错误处理：当浏览器不支持或查询失败时，应用会记录带有上下文的警告信息并保持正常运行，不影响语音功能的常规流程。

* **测试**
  * 新增测试覆盖权限查询失败的两类场景（异常对象或非错误值），验证在拒绝或异常情况下触发相应警告且行为稳定。

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: packages/x/components/sender/hooks/use-speech.ts [hunk 1]
```diff
@@ -44,6 +45,14 @@ export default function useSpeech(
           };
 
           lastPermission = permissionStatus;
```
Comment (kimteayon) [inline packages/x/components/sender/hooks/use-speech.ts]: it would be great to add a test case for this scenario.

**Comment by afc163** [comment]
图片

**Review by afc163 — APPROVED** [review]
