### PR TITLE
fix(x-sdk): add throttling to ChatMessagesStore to prevent "Maximum update depth exceeded" during streaming

### LINKED ISSUE #540: Bubble.List 数据量过多时出现错误：Maximum update depth exceeded
### 重现步骤

在线示例链接：（必填）
https://stackblitz.com/edit/react-fclhfdqc?file=demo.tsx

步骤：
1. 直接运行即可看到
2.
3.

### 当前行为

_No response_

### 预期行为

_No response_

### 上下文

_No response_

### 版本

1.0.5

### 您在哪些浏览器上遇到了这个问题？

Chrome

### PR DESCRIPTION
**Pull request by Afee2019**
## Summary

This PR adds throttling to `ChatMessagesStore.emitListeners()` to prevent "Maximum update depth exceeded"
warnings during SSE streaming.

Fixes #540
Related to #913

## Problem

During SSE streaming (common with LLM integrations), each chunk triggers `setMessages()` → `emitListeners()` →
React re-render. When chunks arrive rapidly, React detects nested updates exceeding its depth limit:

Warning: Maximum update depth exceeded. This can happen when a component
calls setState inside useEffect, but useEffect either doesn't have a
dependency array, or one of the dependencies changes on every render.

## Solution

Add a 50ms throttle to `emitListeners()` with:

- **Leading edge**: First update triggers immediately for responsive UI
- **Trailing edge**: Pending updates are flushed after throttle interval
- **Initialization bypass**: No throttle during constructor to avoid startup delay

## Changes

- Added `throttleTimer`, `pendingEmit`, `throttleInterval` private properties
- Added `throttledEmitListeners()` private method
- Added `setMessagesInternal()` private method with throttle control
- Modified `setMessages()` to use throttled emit
- Modified constructor to use non-throttled initialization

### Before
- Dozens of "Maximum update depth exceeded" warnings during streaming
- Console flooded with warnings affecting DX

### After
- Zero warnings
- Smooth streaming output
- No perceptible delay in UI updates

## Compatibility

- No breaking changes to public API
- `setMessages()` signature unchanged
- All existing tests should pass

## 发布说明

* **新功能**
  * 新增 destroy() 方法，用于清理消息存储并释放节流计时器，便于销毁/重置实例。
* **Bug修复**
  * 优化消息流的节流与发射逻辑，避免高频流式更新导致的深度更新错误，提升实时消息稳定性与性能。

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: packages/x-sdk/src/x-chat/store.ts [hunk 1]
```diff
@@ -98,6 +133,19 @@ export class ChatMessagesStore<T extends { id: number | string }> {
       this.listeners = this.listeners.filter((listener) => listener !== callback);
     };
   };
+
+  /**
+   * Clean up resources (throttle timer) when the store is no longer needed.
+   * Should be called when the component unmounts or the store is disposed.
+   */
+  destroy = () => {
```
Comment (hylin) [inline packages/x-sdk/src/x-chat/store.ts:150]: The `destroy` method is not called anywhere.

Comment (Afee2019) [reply packages/x-sdk/src/x-chat/store.ts:150]: You're right.

The destroy() method is currently exposed as a public API for consumers to call manually when needed (e.g., in React component cleanup). This follows the pattern of providing capability without
forcing usage.

However, I can integrate it into chatMessagesStoreHelper.delete() to ensure automatic cleanup when a store is explicitly deleted:

delete: (key: ConversationKey) => {
  const store = chatMessagesStoreHelper._chatMessagesStores.get(key);
  if (store) {
    store.destroy();
  }
  chatMessagesStoreHelper._chatMessagesStores.delete(key);
}

Would you prefer this approach? Or is the current "opt-in" design acceptable?

Comment (hylin) [reply packages/x-sdk/src/x-chat/store.ts:150]: `store` and `chatMessagesStoreHelper ` didn't ever exposed.
I prefer to automatically call it within useEffect's cleanup function in `useChatStore`.

Comment (Afee2019) [reply packages/x-sdk/src/x-chat/store.ts:150]: Thanks for the feedback! You're right that destroy is not automatically called.

  However, automatically calling destroy() in useEffect cleanup has a problem: when multiple components use the same conversationKey, they share the same store instance (via chatMessagesStoreHelper.get). If one component unmounts and destroys the store, it would break other components still using it.

  Possible solutions:
  1. Reference counting: Track how many subscribers are using each store, only destroy when count reaches 0
  2. Expose destroy in return value: Let users decide when to cleanup: return { ..., destroy: store.destroy }
  3. Integrate with chatMessagesStoreHelper.delete: Make delete() call destroy() internally, so cleanup happens when user explicitly removes the store

  Which approach do you prefer? 
  Or if you think option 1 (reference counting) is acceptable, I can implement it.

Comment (Afee2019) [reply packages/x-sdk/src/x-chat/store.ts:150]: You raise a valid concern about resource cleanup.

However, automatically calling destroy() in useChatStore's useEffect cleanup has a problem: when multiple components share the same conversationKey, they share the same store instance (via chatMessagesStoreHelper.get). If one component unmounts and destroys the store, it would break other components still using it.

I think a better approach is to clean up the timer in the subscribe return function (unsubscribe):

```
subscribe = (callback: () => void) => {
  this.listeners.push(callback);
  return () => {
    this.listeners = this.listeners.filter((listener) => listener !== callback);
    // Clean up timer when no listeners remain
    if (this.listeners.length === 0 && this.throttleTimer) {
      clearTimeout(this.throttleTimer);
      this.throttleTimer = null;
      this.pendingEmit = false;
    }
  };
};
```
This way:
- useSyncExternalStore automatically calls unsubscribe on unmount
- Timer is cleaned up only when ALL subscribers have unsubscribed
- No breaking change to multi-component sharing scenarios
- destroy() method can still be kept for explicit cleanup if needed

What do you think?

Comment (Afee2019) [reply packages/x-sdk/src/x-chat/store.ts:150]: I looked at https://github.com/ant-design/x/issues/1491 - a real user is experiencing exactly the problem this PR fixes, confirming the throttle approach is correct.

Regarding your suggestion to call destroy() in useEffect cleanup: this would break when multiple components share the same conversationKey (they share one store instance via chatMessagesStoreHelper.get).

I propose a cleaner solution - clean up the timer in the unsubscribe callback:
```
subscribe = (callback: () => void) => {
  this.listeners.push(callback);
  return () => {
    this.listeners = this.listeners.filter((listener) => listener !== callback);
    if (this.listeners.length === 0) {
      if (this.throttleTimer) {
        clearTimeout(this.throttleTimer);
        this.throttleTimer = null;
      }
      this.pendingEmit = false;
    }
  };
};
```
This way:
- Timer is auto-cleaned when all subscribers unsubscribe
- Multi-component sharing still works
- No need for explicit destroy() call
- The destroy() method can still be kept for manual cleanup if needed

What do you think?

**Comment by Afee2019** [comment]
## Update: Auto cleanup throttle timer on unsubscribe

Thanks @hylin for the review feedback! I've addressed the resource cleanup concern with a new approach.

### The Problem
As you pointed out, `destroy()` was not being called anywhere, which could lead to:
- Memory leaks from lingering throttle timers
- Potential "setState on unmounted component" warnings

### Why Not Call `destroy()` in `useEffect` Cleanup?
Simply calling `destroy()` in `useChatStore`'s `useEffect` cleanup would break **multi-component sharing scenarios**:
- When multiple components use the same `conversationKey`, they share one store instance via `chatMessagesStoreHelper.get()`
- If one component unmounts and destroys the store, other components still using it would break

### The Solution (commit d8bfce6)
Instead, I've added automatic timer cleanup in the `subscribe` method's unsubscribe callback:

```typescript
subscribe = (callback: () => void) => {
  this.listeners.push(callback);
  return () => {
    this.listeners = this.listeners.filter((listener) => listener !== callback);
    // Clean up throttle timer when no listeners remain
    if (this.listeners.length === 0) {
      if (this.throttleTimer) {
        clearTimeout(this.throttleTimer);
        this.throttleTimer = null;
      }
      this.pendingEmit = false;
    }
  };
};
```

### Benefits
- ✅ **Automatic cleanup**: Timer is cleaned when ALL subscribers unsubscribe
- ✅ **Multi-component safe**: Shared stores work correctly - cleanup only happens when the last subscriber leaves
- ✅ **No manual calls needed**: `useSyncExternalStore` automatically calls unsubscribe on unmount
- ✅ **`destroy()` preserved**: Still available for explicit cleanup if needed (e.g., when calling `chatMessagesStoreHelper.delete()`)

---

Note: This PR also fixes [Issue #1491](https://github.com/ant-design/x/issues/1491) where users report the same "Maximum update depth exceeded" error with `@ant-design/x` 2.1.0.

File: packages/x-sdk/src/x-chat/store.ts (hunk 1 above)
Comment (hylin) [reply packages/x-sdk/src/x-chat/store.ts:150]: Sounds good!

**Review by hylin — APPROVED** [review]
