### PR TITLE
fix(ThoughtChain): fix the issue where title block-level elements cannot be displayed when collapsible is enabled

### LINKED ISSUE #1150: ThoughtChain - Item 当title是ReactNode 并且开启了折叠 collapsible 之后无法渲染Title
### 重现步骤

引用官方文档示例:   https://ant-design-x.antgroup.com/components/thought-chain-cn#thought-chain-demo-collapsible

其中修改item
.....
const items: ThoughtChainProps['items'] = [
  {
    key: 'item-1',
    title: <div >Click me to expand the content</div>,  //修改成ReactNode
    description: 'Collapsible',
    content: mockContent,
    status: 'success',
  },
  {
    key: 'item-2',
    title: 'Click me to expand the content',
    description: 'Collapsible',
    content: mockContent,
    status: 'pending',
  },
];
....

 <ThoughtChain items={items}  collapsible />

### 当前行为

无法渲染出ReactNode 

Image

### 预期行为

正确渲染出Title

### 上下文

_No response_

### 版本

1.3.0

### 您在哪些浏览器上遇到了这个问题？

_No response_

### PR DESCRIPTION
**Pull request by IsDyh01**
[中文版模板 / Chinese template](https://github.com/ant-design/x/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [✅] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ⌨️ Accessibility improvement
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx
fix #1150 

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://x.ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

## Summary by CodeRabbit

- 用户体验  
  - 仅在标题溢出时显示气泡提示，Tooltip 根据 RTL/非 RTL 调整显示方向，避免无谓弹出。  
- 样式  
  - 标题行改为弹性布局，新增标题内容样式支持文本省略与溢出处理，折叠图标与文本对齐改进。  
- 重构  
  - 标题渲染改为带容器的结构并加入手动溢出检测与 ResizeObserver，其他行为保持不变。  
- Chores  
  - 示例与样式导入改为类型导入与调整顺序，未改变运行时行为。

### CODE REVIEW

**Comment by IsDyh01** [comment]
@kimteayon  
这个修改是把原来title结构中的Typography.Text替换为了普通的div元素，然后手动检测title内容长度判断是否需要展示tooltip，这样就title属性就可以直接传递块级元素了。

**Comment by kimteayon** [comment]
> @kimteayon 这个修改是把原来title结构中的Typography.Text替换为了普通的div元素，然后手动检测title内容长度判断是否需要展示tooltip，这样就title属性就可以直接传递块级元素了。

您的改动很不错，辛苦帮忙确认下标题加粗的效果
image

File: components/thought-chain/style/index.ts [hunk 1]
```diff
@@ -183,9 +182,22 @@ const genThoughtChainItemStyle: GenerateThoughtChainItemStyle = (token) => {
...
+
+            // 文本内容样式
+            [`& ${itemCls}-title-content`]: {
+              flex: 1,
+              minWidth: 0,
+              overflow: 'hidden',
+              textOverflow: 'ellipsis',
+              whiteSpace: 'nowrap',
+              display: 'inline-block',
             },
```
[the remark this answers is not in the document]
Comment (kimteayon) [reply components/thought-chain/style/index.ts]: 辛苦帮忙确认下

File: components/thought-chain/Item.tsx [hunk 2]
```diff
@@ -162,28 +182,30 @@ const ThoughtChainNode: React.FC<ThoughtChainNodeProps> = (props) => {
...
+                    rotate={contentOpen ? -90 : 0}
+                  />
+                ) : (
+                  <RightOutlined
+                    className={`${itemCls}-collapse-icon`}
+                    rotate={contentOpen ? 90 : 0}
+                  />
+                ))}
+
+              <span ref={textRef} className={`${itemCls}-title-content`}>
```
Comment (kimteayon) [inline components/thought-chain/Item.tsx]: 这里的span帮忙改成div吧 如果内部是div 会报错 感谢🙏

Comment (IsDyh01) [reply components/thought-chain/Item.tsx]: 感谢指正,已修改
